<?php

return array(
    'label' => $this->module->getMenuIcon('icon/report') . 'รายงาน',
    'visible' => Yii::app()->user->checkPermission('report.*'),
    'items' => array(
        array(
            'label' => 'ระบบรายงาน',
            'visible' => Yii::app()->user->checkPermission(array(
                'report.reportExamCard',
                'report.reportPaymentSlip',
                'report.reportNameList',
                'report.reportNameListByObjective',
                'report.reportNameSignature',
                'report.reportPaymentStatus',
                'report.reportApplication',
                'report.reportPayment',
                'report.reportReceipt',
                'report.reportIncome',
                'report.reportExpenditure',
                'report.reportTestResult',
                'report.reportTestResultReply',
                'report.reportTestResultEnvelope',
                'report.reportTestResultCover',
                'report.reportMemberProfile',
                'report.reportExamSet',
                'report.reportBorderLine',
                'report.reportExamApprove',
                'report.reportExamRawData',
                'report.reportBarcode',
                'report.reportExportCertificateFromXls',
            )),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '01. บัตรประจำตัวสอบ',
            'url' => array('reportExamCard/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportExamCard'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '02. ใบชำระเงิน',
            'url' => array('reportPaymentSlip/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportPaymentSlip'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '03. รายชื่อสำหรับติดหน้าห้องสอบ',
            'url' => array('reportNameList/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportNameList'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '04. รายชื่อผู้เข้าสอบแยกตามวัตถุประสงค์ในการสอบ',
            'url' => array('reportNameListByObjective/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportNameListByObjective'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '05. ใบเซ็นต์ชื่อ',
            'url' => array('reportNameSignature/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportNameSignature'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '06. สถานะการชำระเงิน',
            'url' => array('reportPaymentStatus/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportPaymentStatus'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '07. สถิติการสมัคร',
            'url' => array('reportApplication/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportApplication'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '08. รายงานการชำระเงิน',
            'url' => array('reportPayment/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportPayment'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '09. ใบเสร็จรับเงิน',
            'url' => array('reportReceipt/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportReceipt'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '10. รายงานรายได้จากการสมัครสอบ',
            'url' => array('reportIncome/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportIncome'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '11. รายงานรายจ่าย',
            'url' => array('reportExpenditure/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportExpenditure'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '12. ใบรับรองผลสอบภาษาอังกฤษ',
            'url' => array('reportTestResult/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportTestResult'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '13. หนังสือแจ้งผลการทดสอบภาษาอังกฤษ',
            'url' => array('reportTestResultReply/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportTestResultReply'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '14. ซองสำหรับส่งผลสอบ',
            'url' => array('reportTestResultEnvelope/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportTestResultEnvelope'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '15. ใบปะหน้าซองสำหรับส่งผลสอบให้หน่วยงาน',
            'url' => array('reportTestResultCover/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportTestResultCover'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '16. ประวัติการสอบรายบุคคล',
            'url' => array('reportMemberProfile/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportMemberProfile'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '17. ประวัติการสอบสำหรับจัดชุดข้อสอบ',
            'url' => array('reportExamSet/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportExamSet'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '18. รายงานบุคคลที่ได้คะแนนเท่ากับ Border Line',
            'url' => array('reportBorderLine/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportBorderLine'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '19. รายงานการตรวจข้อสอบ',
            'url' => array('reportExamApprove/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportExamApprove'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '20. ข้อมูลการทำข้อสอบ',
            'url' => array('reportExamRawData/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportExamRawData'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '21. บาร์โค๊ดสำหรับติดบนกระดาษคำตอบ',
            'url' => array('reportBarcode/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportBarcode'),
        ),
        array(
            'label' => $this->module->getMenuIcon('icon/page') . '22. พิมพ์ใบรับรองจากไฟล์ Excel',
            'url' => array('reportExportCertificateFromXls/index'),
            'visible' => Yii::app()->user->checkPermission('report.reportExportCertificateFromXls'),
        ),
    ),
    'visible' => Yii::app()->user->checkPermission(array(
        'report.reportExamCard',
        'report.reportPaymentSlip',
        'report.reportNameList',
        'report.reportNameListByObjective',
        'report.reportNameSignature',
        'report.reportPaymentStatus',
        'report.reportApplication',
        'report.reportPayment',
        'report.reportReceipt',
        'report.reportIncome',
        'report.reportExpenditure',
        'report.reportTestResult',
        'report.reportTestResultReply',
        'report.reportTestResultEnvelope',
        'report.reportTestResultCover',
        'report.reportMemberProfile',
        'report.reportExamSet',
        'report.reportBorderLine',
        'report.reportExamApprove',
        'report.reportExamRawData',
        'report.reportBarcode',
        'report.reportExportCertificateFromXls',
    )),
);
