<?php

/**
 * This is the model base class for the table "code_title".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CodeTitle".
 *
 * Columns in table "code_title" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $name_th
 * @property string $name_en
 *
 */
abstract class BaseCodeTitle extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'code_title';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CodeTitle|CodeTitles', $n);
	}

	public static function representingColumn() {
		return 'name_th';
	}

	public function rules() {
		return array(
			array('name_th, name_en', 'length', 'max'=>60),
			array('name_th, name_en', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name_th, name_en', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name_th' => Yii::t('app', 'Name Th'),
			'name_en' => Yii::t('app', 'Name En'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name_th', $this->name_th, true);
		$criteria->compare('name_en', $this->name_en, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}