<?php

/**
 * This is the model base class for the table "web_sms_item".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "WebSmsItem".
 *
 * Columns in table "web_sms_item" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $web_sms_id
 * @property string $address_to
 * @property string $address_from
 * @property integer $status
 * @property string $send_date
 * @property string $msg
 *
 */
abstract class BaseWebSmsItem extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'web_sms_item';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'WebSmsItem|WebSmsItems', $n);
	}

	public static function representingColumn() {
		return 'address_to';
	}

	public function rules() {
		return array(
			array('web_sms_id', 'required'),
			array('status', 'numerical', 'integerOnly'=>true),
			array('web_sms_id', 'length', 'max'=>10),
			array('address_to, address_from', 'length', 'max'=>100),
			array('send_date, msg', 'safe'),
			array('address_to, address_from, status, send_date, msg', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, web_sms_id, address_to, address_from, status, send_date, msg', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'web_sms_id' => Yii::t('app', 'Web Sms'),
			'address_to' => Yii::t('app', 'Address To'),
			'address_from' => Yii::t('app', 'Address From'),
			'status' => Yii::t('app', 'Status'),
			'send_date' => Yii::t('app', 'Send Date'),
			'msg' => Yii::t('app', 'Msg'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('web_sms_id', $this->web_sms_id, true);
		$criteria->compare('address_to', $this->address_to, true);
		$criteria->compare('address_from', $this->address_from, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('send_date', $this->send_date, true);
		$criteria->compare('msg', $this->msg, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}