<?php

/**
 * This is the model base class for the table "exam_set_task".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ExamSetTask".
 *
 * Columns in table "exam_set_task" available as properties of the model,
 * followed by relations of table "exam_set_task" available as properties of the model.
 *
 * @property string $exam_set_id
 * @property integer $task_no
 * @property integer $task_num
 * @property string $exam_question_method_id
 * @property integer $order_no
 * @property integer $is_auto_check
 *
 * @property ExamQuestionMethod $examQuestionMethod
 * @property ExamSet $examSet
 */
abstract class BaseExamSetTask extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'exam_set_task';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ExamSetTask|ExamSetTasks', $n);
	}

	public static function representingColumn() {
		return 'exam_set_id';
	}

	public function rules() {
		return array(
			array('exam_set_id, task_no, exam_question_method_id', 'required'),
			array('task_no, task_num, order_no, is_auto_check', 'numerical', 'integerOnly'=>true),
			array('exam_set_id, exam_question_method_id', 'length', 'max'=>10),
			array('task_num, order_no, is_auto_check', 'default', 'setOnEmpty' => true, 'value' => null),
			array('exam_set_id, task_no, task_num, exam_question_method_id, order_no, is_auto_check', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'examQuestionMethod' => array(self::BELONGS_TO, 'ExamQuestionMethod', 'exam_question_method_id'),
			'examSet' => array(self::BELONGS_TO, 'ExamSet', 'exam_set_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'exam_set_id' => null,
			'task_no' => Yii::t('app', 'Task No'),
			'task_num' => Yii::t('app', 'Task Num'),
			'exam_question_method_id' => null,
			'order_no' => Yii::t('app', 'Order No'),
			'is_auto_check' => Yii::t('app', 'Is Auto Check'),
			'examQuestionMethod' => null,
			'examSet' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('exam_set_id', $this->exam_set_id);
		$criteria->compare('task_no', $this->task_no);
		$criteria->compare('task_num', $this->task_num);
		$criteria->compare('exam_question_method_id', $this->exam_question_method_id);
		$criteria->compare('order_no', $this->order_no);
		$criteria->compare('is_auto_check', $this->is_auto_check);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}