<?php

/**
 * This is the model base class for the table "account_tag".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AccountTag".
 *
 * Columns in table "account_tag" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $account_id
 * @property string $tag_id
 *
 */
abstract class BaseAccountTag extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'account_tag';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AccountTag|AccountTags', $n);
	}

	public static function representingColumn() {
		return array(
			'account_id',
			'tag_id',
		);
	}

	public function rules() {
		return array(
			array('account_id, tag_id', 'required'),
			array('account_id, tag_id', 'length', 'max'=>10),
			array('account_id, tag_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'account_id' => null,
			'tag_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('account_id', $this->account_id);
		$criteria->compare('tag_id', $this->tag_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}