<?php

/**
 * This is the model base class for the table "account_oversea_posting".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AccountOverseaPosting".
 *
 * Columns in table "account_oversea_posting" available as properties of the model,
 * followed by relations of table "account_oversea_posting" available as properties of the model.
 *
 * @property string $account_id
 * @property string $op_number
 * @property string $office
 * @property string $city
 * @property string $country
 * @property integer $year_start
 * @property integer $year_end
 *
 * @property Account $account
 */
abstract class BaseAccountOverseaPosting extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'account_oversea_posting';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AccountOverseaPosting|AccountOverseaPostings', $n);
	}

	public static function representingColumn() {
		return 'office';
	}

	public function rules() {
		return array(
			array('account_id, op_number', 'required'),
			array('year_start, year_end', 'numerical', 'integerOnly'=>true),
			array('account_id, op_number', 'length', 'max'=>10),
			array('office, city, country', 'length', 'max'=>60),
			array('office, city, country, year_start, year_end', 'default', 'setOnEmpty' => true, 'value' => null),
			array('account_id, op_number, office, city, country, year_start, year_end', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'account' => array(self::BELONGS_TO, 'Account', 'account_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'account_id' => null,
			'op_number' => Yii::t('app', 'Op Number'),
			'office' => Yii::t('app', 'Office'),
			'city' => Yii::t('app', 'City'),
			'country' => Yii::t('app', 'Country'),
			'year_start' => Yii::t('app', 'Year Start'),
			'year_end' => Yii::t('app', 'Year End'),
			'account' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('account_id', $this->account_id);
		$criteria->compare('op_number', $this->op_number, true);
		$criteria->compare('office', $this->office, true);
		$criteria->compare('city', $this->city, true);
		$criteria->compare('country', $this->country, true);
		$criteria->compare('year_start', $this->year_start);
		$criteria->compare('year_end', $this->year_end);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}