<?php

/**
 * This is the model base class for the table "account_profile_diplomat_thai".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AccountProfileDiplomatThai".
 *
 * Columns in table "account_profile_diplomat_thai" available as properties of the model,
 * followed by relations of table "account_profile_diplomat_thai" available as properties of the model.
 *
 * @property string $account_id
 * @property string $gender
 * @property string $title_id_th
 * @property string $title_th
 * @property string $firstname_th
 * @property string $lastname_th
 * @property string $title_id_en
 * @property string $title_en
 * @property string $firstname_en
 * @property string $lastname_en
 * @property string $birth_date
 * @property integer $religion_id
 * @property string $nationality_id
 * @property string $diplomat_type
 * @property string $diplomat_position
 * @property string $diplomat_level
 * @property string $diplomat_level_other
 * @property string $diplomat_office
 * @property integer $oversea_posting
 * @property string $contact_voip
 * @property string $contact_fax_country
 * @property string $contact_fax
 * @property string $contact_mobile_country
 * @property string $contact_mobile
 * @property string $contact_email
 * @property string $educate_highschool
 * @property string $educate_highschool_country
 * @property string $educate_bachelor
 * @property string $educate_bachelor_year_from
 * @property string $educate_bachelor_year_to
 * @property string $educate_bachelor_university
 * @property string $educate_bachelor_country
 * @property string $educate_master
 * @property string $educate_master_year_from
 * @property string $educate_master_year_to
 * @property string $educate_master_university
 * @property string $educate_master_country
 * @property string $educate_phd
 * @property string $educate_phd_year_from
 * @property string $educate_phd_year_to
 * @property string $educate_phd_university
 * @property string $educate_phd_country
 * @property string $religion_other
 * @property integer $work_year
 * @property string $emp_pic_file
 * @property string $work_unit
 * @property string $work_unit_th
 *
 * @property Account $account
 */
abstract class BaseAccountProfileDiplomatThai extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'account_profile_diplomat_thai';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AccountProfileDiplomatThai|AccountProfileDiplomatThais', $n);
	}

	public static function representingColumn() {
		return 'gender';
	}

	public function rules() {
		return array(
			array('account_id', 'required'),
			array('religion_id, oversea_posting, work_year', 'numerical', 'integerOnly'=>true),
			array('account_id', 'length', 'max'=>10),
			array('gender, title_id_th, title_id_en', 'length', 'max'=>1),
			array('title_th, firstname_th, lastname_th, title_en, firstname_en, lastname_en, diplomat_type, diplomat_position, diplomat_level, diplomat_level_other, contact_voip, contact_fax_country, contact_fax, contact_mobile_country, contact_mobile, contact_email, educate_highschool, educate_highschool_country, educate_bachelor, educate_bachelor_year_from, educate_bachelor_year_to, educate_bachelor_university, educate_bachelor_country, educate_master, educate_master_year_from, educate_master_year_to, educate_master_university, educate_master_country, educate_phd, educate_phd_year_from, educate_phd_year_to, educate_phd_university, educate_phd_country, religion_other', 'length', 'max'=>60),
			array('nationality_id', 'length', 'max'=>3),
			array('diplomat_office, work_unit, work_unit_th', 'length', 'max'=>250),
			array('emp_pic_file', 'length', 'max'=>100),
			array('birth_date', 'safe'),
			array('gender, title_id_th, title_th, firstname_th, lastname_th, title_id_en, title_en, firstname_en, lastname_en, birth_date, religion_id, nationality_id, diplomat_type, diplomat_position, diplomat_level, diplomat_level_other, diplomat_office, oversea_posting, contact_voip, contact_fax_country, contact_fax, contact_mobile_country, contact_mobile, contact_email, educate_highschool, educate_highschool_country, educate_bachelor, educate_bachelor_year_from, educate_bachelor_year_to, educate_bachelor_university, educate_bachelor_country, educate_master, educate_master_year_from, educate_master_year_to, educate_master_university, educate_master_country, educate_phd, educate_phd_year_from, educate_phd_year_to, educate_phd_university, educate_phd_country, religion_other, work_year, emp_pic_file, work_unit, work_unit_th', 'default', 'setOnEmpty' => true, 'value' => null),
			array('account_id, gender, title_id_th, title_th, firstname_th, lastname_th, title_id_en, title_en, firstname_en, lastname_en, birth_date, religion_id, nationality_id, diplomat_type, diplomat_position, diplomat_level, diplomat_level_other, diplomat_office, oversea_posting, contact_voip, contact_fax_country, contact_fax, contact_mobile_country, contact_mobile, contact_email, educate_highschool, educate_highschool_country, educate_bachelor, educate_bachelor_year_from, educate_bachelor_year_to, educate_bachelor_university, educate_bachelor_country, educate_master, educate_master_year_from, educate_master_year_to, educate_master_university, educate_master_country, educate_phd, educate_phd_year_from, educate_phd_year_to, educate_phd_university, educate_phd_country, religion_other, work_year, emp_pic_file, work_unit, work_unit_th', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'account' => array(self::BELONGS_TO, 'Account', 'account_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'account_id' => null,
			'gender' => Yii::t('app', 'Gender'),
			'title_id_th' => Yii::t('app', 'Title Id Th'),
			'title_th' => Yii::t('app', 'Title Th'),
			'firstname_th' => Yii::t('app', 'Firstname Th'),
			'lastname_th' => Yii::t('app', 'Lastname Th'),
			'title_id_en' => Yii::t('app', 'Title Id En'),
			'title_en' => Yii::t('app', 'Title En'),
			'firstname_en' => Yii::t('app', 'Firstname En'),
			'lastname_en' => Yii::t('app', 'Lastname En'),
			'birth_date' => Yii::t('app', 'Birth Date'),
			'religion_id' => Yii::t('app', 'Religion'),
			'nationality_id' => Yii::t('app', 'Nationality'),
			'diplomat_type' => Yii::t('app', 'Diplomat Type'),
			'diplomat_position' => Yii::t('app', 'Diplomat Position'),
			'diplomat_level' => Yii::t('app', 'Diplomat Level'),
			'diplomat_level_other' => Yii::t('app', 'Diplomat Level Other'),
			'diplomat_office' => Yii::t('app', 'Diplomat Office'),
			'oversea_posting' => Yii::t('app', 'Oversea Posting'),
			'contact_voip' => Yii::t('app', 'Contact Voip'),
			'contact_fax_country' => Yii::t('app', 'Contact Fax Country'),
			'contact_fax' => Yii::t('app', 'Contact Fax'),
			'contact_mobile_country' => Yii::t('app', 'Contact Mobile Country'),
			'contact_mobile' => Yii::t('app', 'Contact Mobile'),
			'contact_email' => Yii::t('app', 'Contact Email'),
			'educate_highschool' => Yii::t('app', 'Educate Highschool'),
			'educate_highschool_country' => Yii::t('app', 'Educate Highschool Country'),
			'educate_bachelor' => Yii::t('app', 'Educate Bachelor'),
			'educate_bachelor_year_from' => Yii::t('app', 'Educate Bachelor Year From'),
			'educate_bachelor_year_to' => Yii::t('app', 'Educate Bachelor Year To'),
			'educate_bachelor_university' => Yii::t('app', 'Educate Bachelor University'),
			'educate_bachelor_country' => Yii::t('app', 'Educate Bachelor Country'),
			'educate_master' => Yii::t('app', 'Educate Master'),
			'educate_master_year_from' => Yii::t('app', 'Educate Master Year From'),
			'educate_master_year_to' => Yii::t('app', 'Educate Master Year To'),
			'educate_master_university' => Yii::t('app', 'Educate Master University'),
			'educate_master_country' => Yii::t('app', 'Educate Master Country'),
			'educate_phd' => Yii::t('app', 'Educate Phd'),
			'educate_phd_year_from' => Yii::t('app', 'Educate Phd Year From'),
			'educate_phd_year_to' => Yii::t('app', 'Educate Phd Year To'),
			'educate_phd_university' => Yii::t('app', 'Educate Phd University'),
			'educate_phd_country' => Yii::t('app', 'Educate Phd Country'),
			'religion_other' => Yii::t('app', 'Religion Other'),
			'work_year' => Yii::t('app', 'Work Year'),
			'emp_pic_file' => Yii::t('app', 'Emp Pic File'),
			'work_unit' => Yii::t('app', 'Work Unit'),
			'work_unit_th' => Yii::t('app', 'Work Unit Th'),
			'account' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('account_id', $this->account_id);
		$criteria->compare('gender', $this->gender, true);
		$criteria->compare('title_id_th', $this->title_id_th, true);
		$criteria->compare('title_th', $this->title_th, true);
		$criteria->compare('firstname_th', $this->firstname_th, true);
		$criteria->compare('lastname_th', $this->lastname_th, true);
		$criteria->compare('title_id_en', $this->title_id_en, true);
		$criteria->compare('title_en', $this->title_en, true);
		$criteria->compare('firstname_en', $this->firstname_en, true);
		$criteria->compare('lastname_en', $this->lastname_en, true);
		$criteria->compare('birth_date', $this->birth_date, true);
		$criteria->compare('religion_id', $this->religion_id);
		$criteria->compare('nationality_id', $this->nationality_id, true);
		$criteria->compare('diplomat_type', $this->diplomat_type, true);
		$criteria->compare('diplomat_position', $this->diplomat_position, true);
		$criteria->compare('diplomat_level', $this->diplomat_level, true);
		$criteria->compare('diplomat_level_other', $this->diplomat_level_other, true);
		$criteria->compare('diplomat_office', $this->diplomat_office, true);
		$criteria->compare('oversea_posting', $this->oversea_posting);
		$criteria->compare('contact_voip', $this->contact_voip, true);
		$criteria->compare('contact_fax_country', $this->contact_fax_country, true);
		$criteria->compare('contact_fax', $this->contact_fax, true);
		$criteria->compare('contact_mobile_country', $this->contact_mobile_country, true);
		$criteria->compare('contact_mobile', $this->contact_mobile, true);
		$criteria->compare('contact_email', $this->contact_email, true);
		$criteria->compare('educate_highschool', $this->educate_highschool, true);
		$criteria->compare('educate_highschool_country', $this->educate_highschool_country, true);
		$criteria->compare('educate_bachelor', $this->educate_bachelor, true);
		$criteria->compare('educate_bachelor_year_from', $this->educate_bachelor_year_from, true);
		$criteria->compare('educate_bachelor_year_to', $this->educate_bachelor_year_to, true);
		$criteria->compare('educate_bachelor_university', $this->educate_bachelor_university, true);
		$criteria->compare('educate_bachelor_country', $this->educate_bachelor_country, true);
		$criteria->compare('educate_master', $this->educate_master, true);
		$criteria->compare('educate_master_year_from', $this->educate_master_year_from, true);
		$criteria->compare('educate_master_year_to', $this->educate_master_year_to, true);
		$criteria->compare('educate_master_university', $this->educate_master_university, true);
		$criteria->compare('educate_master_country', $this->educate_master_country, true);
		$criteria->compare('educate_phd', $this->educate_phd, true);
		$criteria->compare('educate_phd_year_from', $this->educate_phd_year_from, true);
		$criteria->compare('educate_phd_year_to', $this->educate_phd_year_to, true);
		$criteria->compare('educate_phd_university', $this->educate_phd_university, true);
		$criteria->compare('educate_phd_country', $this->educate_phd_country, true);
		$criteria->compare('religion_other', $this->religion_other, true);
		$criteria->compare('work_year', $this->work_year);
		$criteria->compare('emp_pic_file', $this->emp_pic_file, true);
		$criteria->compare('work_unit', $this->work_unit, true);
		$criteria->compare('work_unit_th', $this->work_unit_th, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}