<?php

/**
 * This is the model base class for the table "code_objective".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CodeObjective".
 *
 * Columns in table "code_objective" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $name_th
 * @property string $name_en
 * @property string $description
 * @property integer $is_private
 * @property string $period_start
 * @property string $period_end
 *
 */
abstract class BaseCodeObjective extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'code_objective';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CodeObjective|CodeObjectives', $n);
	}

	public static function representingColumn() {
		return 'name_th';
	}

	public function rules() {
		return array(
			array('is_private', 'numerical', 'integerOnly'=>true),
			array('name_th, name_en', 'length', 'max'=>160),
			array('description, period_start, period_end', 'safe'),
			array('name_th, name_en, description, is_private, period_start, period_end', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name_th, name_en, description, is_private, period_start, period_end', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name_th' => Yii::t('app', 'Name Th'),
			'name_en' => Yii::t('app', 'Name En'),
			'description' => Yii::t('app', 'Description'),
			'is_private' => Yii::t('app', 'Is Private'),
			'period_start' => Yii::t('app', 'Period Start'),
			'period_end' => Yii::t('app', 'Period End'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name_th', $this->name_th, true);
		$criteria->compare('name_en', $this->name_en, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('is_private', $this->is_private);
		$criteria->compare('period_start', $this->period_start, true);
		$criteria->compare('period_end', $this->period_end, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}