<?php

/**
 * This is the model base class for the table "exam_set_approver".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ExamSetApprover".
 *
 * Columns in table "exam_set_approver" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $exam_schedule_id
 * @property string $exam_set_id
 * @property string $approver_id
 * @property integer $exam_application_id
 * @property integer $exam_type_id
 * @property integer $exam_subject_id
 * @property string $created
 * @property string $modified
 * @property string $raw_data
 * @property string $grade
 * @property integer $score
 *
 */
abstract class BaseExamSetApprover extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'exam_set_approver';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ExamSetApprover|ExamSetApprovers', $n);
	}

	public static function representingColumn() {
		return 'exam_set_id';
	}

	public function rules() {
		return array(
			array('exam_schedule_id, exam_set_id, approver_id', 'required'),
			array('exam_schedule_id, exam_application_id, exam_type_id, exam_subject_id, score', 'numerical', 'integerOnly'=>true),
			array('exam_set_id, grade', 'length', 'max'=>10),
			array('approver_id', 'length', 'max'=>2),
			array('created, modified, raw_data', 'safe'),
			array('exam_application_id, exam_type_id, exam_subject_id, created, modified, raw_data, grade, score', 'default', 'setOnEmpty' => true, 'value' => null),
			array('exam_schedule_id, exam_set_id, approver_id, exam_application_id, exam_type_id, exam_subject_id, created, modified, raw_data, grade, score', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'exam_schedule_id' => Yii::t('app', 'Exam Schedule'),
			'exam_set_id' => Yii::t('app', 'Exam Set'),
			'approver_id' => Yii::t('app', 'Approver'),
			'exam_application_id' => Yii::t('app', 'Exam Application'),
			'exam_type_id' => Yii::t('app', 'Exam Type'),
			'exam_subject_id' => Yii::t('app', 'Exam Subject'),
			'created' => Yii::t('app', 'Created'),
			'modified' => Yii::t('app', 'Modified'),
			'raw_data' => Yii::t('app', 'Raw Data'),
			'grade' => Yii::t('app', 'Grade'),
			'score' => Yii::t('app', 'Score'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('exam_schedule_id', $this->exam_schedule_id);
		$criteria->compare('exam_set_id', $this->exam_set_id, true);
		$criteria->compare('approver_id', $this->approver_id, true);
		$criteria->compare('exam_application_id', $this->exam_application_id);
		$criteria->compare('exam_type_id', $this->exam_type_id);
		$criteria->compare('exam_subject_id', $this->exam_subject_id);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('modified', $this->modified, true);
		$criteria->compare('raw_data', $this->raw_data, true);
		$criteria->compare('grade', $this->grade, true);
		$criteria->compare('score', $this->score);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}