<?php

/**
 * This is the model base class for the table "expenditure".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Expenditure".
 *
 * Columns in table "expenditure" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property integer $expenditure_type_id
 * @property string $expenditure_date
 * @property string $comment
 * @property string $amount
 * @property string $user_id
 * @property string $created
 * @property string $modified
 * @property string $description
 *
 */
abstract class BaseExpenditure extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'expenditure';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Expenditure|Expenditures', $n);
	}

	public static function representingColumn() {
		return 'amount';
	}

	public function rules() {
		return array(
			array('expenditure_type_id', 'required'),
			array('expenditure_type_id', 'numerical', 'integerOnly'=>true),
			array('amount', 'length', 'max'=>18),
			array('user_id', 'length', 'max'=>10),
			array('expenditure_date, comment, created, modified, description', 'safe'),
			array('expenditure_date, comment, amount, user_id, created, modified, description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, expenditure_type_id, expenditure_date, comment, amount, user_id, created, modified, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'expenditure_type_id' => Yii::t('app', 'Expenditure Type'),
			'expenditure_date' => Yii::t('app', 'Expenditure Date'),
			'comment' => Yii::t('app', 'Comment'),
			'amount' => Yii::t('app', 'Amount'),
			'user_id' => Yii::t('app', 'User'),
			'created' => Yii::t('app', 'Created'),
			'modified' => Yii::t('app', 'Modified'),
			'description' => Yii::t('app', 'Description'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('expenditure_type_id', $this->expenditure_type_id);
		$criteria->compare('expenditure_date', $this->expenditure_date, true);
		$criteria->compare('comment', $this->comment, true);
		$criteria->compare('amount', $this->amount, true);
		$criteria->compare('user_id', $this->user_id, true);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('modified', $this->modified, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}