<?php

/**
 * This is the model base class for the table "application_score".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ApplicationScore".
 *
 * Columns in table "application_score" available as properties of the model,
 * followed by relations of table "application_score" available as properties of the model.
 *
 * @property string $id
 * @property string $exam_application_id
 * @property string $exam_topic_id
 * @property integer $score
 * @property integer $score_revise
 * @property integer $reviser_user_id
 * @property integer $is_upload
 *
 * @property ExamApplication $examApplication
 * @property ExamTopic $examTopic
 */
abstract class BaseApplicationScore extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'application_score';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ApplicationScore|ApplicationScores', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('exam_application_id, exam_topic_id', 'required'),
			array('score, score_revise, reviser_user_id, is_upload', 'numerical', 'integerOnly'=>true),
			array('exam_application_id, exam_topic_id', 'length', 'max'=>10),
			array('score, score_revise, reviser_user_id, is_upload', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, exam_application_id, exam_topic_id, score, score_revise, reviser_user_id, is_upload', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'examApplication' => array(self::BELONGS_TO, 'ExamApplication', 'exam_application_id'),
			'examTopic' => array(self::BELONGS_TO, 'ExamTopic', 'exam_topic_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'exam_application_id' => null,
			'exam_topic_id' => null,
			'score' => Yii::t('app', 'Score'),
			'score_revise' => Yii::t('app', 'Score Revise'),
			'reviser_user_id' => Yii::t('app', 'Reviser User'),
			'is_upload' => Yii::t('app', 'Is Upload'),
			'examApplication' => null,
			'examTopic' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('exam_application_id', $this->exam_application_id);
		$criteria->compare('exam_topic_id', $this->exam_topic_id);
		$criteria->compare('score', $this->score);
		$criteria->compare('score_revise', $this->score_revise);
		$criteria->compare('reviser_user_id', $this->reviser_user_id);
		$criteria->compare('is_upload', $this->is_upload);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}