<?php

/**
 * This is the model base class for the table "omr_source".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OmrSource".
 *
 * Columns in table "omr_source" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $name
 * @property string $created
 * @property string $modified
 * @property integer $status
 * @property string $zip_path
 *
 */
abstract class BaseOmrSource extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'omr_source';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OmrSource|OmrSources', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('status', 'numerical', 'integerOnly'=>true),
			array('name, zip_path', 'length', 'max'=>160),
			array('created, modified', 'safe'),
			array('name, created, modified, status, zip_path', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, created, modified, status, zip_path', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'created' => Yii::t('app', 'Created'),
			'modified' => Yii::t('app', 'Modified'),
			'status' => Yii::t('app', 'Status'),
			'zip_path' => Yii::t('app', 'Zip Path'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('modified', $this->modified, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('zip_path', $this->zip_path, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}