<?php

/**
 * This is the model base class for the table "web_menu_item".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "WebMenuItem".
 *
 * Columns in table "web_menu_item" available as properties of the model,
 * followed by relations of table "web_menu_item" available as properties of the model.
 *
 * @property string $id
 * @property string $web_menu_id
 * @property string $name
 * @property string $url
 * @property string $name_en
 * @property integer $order_no
 *
 * @property WebMenu $webMenu
 */
abstract class BaseWebMenuItem extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'web_menu_item';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'WebMenuItem|WebMenuItems', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('web_menu_id', 'required'),
			array('order_no', 'numerical', 'integerOnly'=>true),
			array('web_menu_id', 'length', 'max'=>10),
			array('name, name_en', 'length', 'max'=>150),
			array('url', 'safe'),
			array('name, url, name_en, order_no', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, web_menu_id, name, url, name_en, order_no', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'webMenu' => array(self::BELONGS_TO, 'WebMenu', 'web_menu_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'web_menu_id' => null,
			'name' => Yii::t('app', 'Name'),
			'url' => Yii::t('app', 'Url'),
			'name_en' => Yii::t('app', 'Name En'),
			'order_no' => Yii::t('app', 'Order No'),
			'webMenu' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('web_menu_id', $this->web_menu_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('name_en', $this->name_en, true);
		$criteria->compare('order_no', $this->order_no);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}