<?php

/**
 * This is the model base class for the table "key_counter".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "KeyCounter".
 *
 * Columns in table "key_counter" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property integer $num
 * @property string $created
 * @property string $modified
 *
 */
abstract class BaseKeyCounter extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'key_counter';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'KeyCounter|KeyCounters', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('id', 'required'),
			array('num', 'numerical', 'integerOnly'=>true),
			array('id', 'length', 'max'=>64),
			array('created, modified', 'safe'),
			array('num, created, modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, num, created, modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'num' => Yii::t('app', 'Num'),
			'created' => Yii::t('app', 'Created'),
			'modified' => Yii::t('app', 'Modified'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('num', $this->num);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('modified', $this->modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}