<?php

/**
 * This is the model base class for the table "time_dimension".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TimeDimension".
 *
 * Columns in table "time_dimension" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $db_date
 * @property integer $year
 * @property integer $month
 * @property integer $day
 * @property integer $quarter
 * @property integer $week
 * @property string $day_name
 * @property string $month_name
 * @property string $holiday_flag
 * @property string $weekend_flag
 * @property string $event
 *
 */
abstract class BaseTimeDimension extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'time_dimension';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TimeDimension|TimeDimensions', $n);
	}

	public static function representingColumn() {
		return 'db_date';
	}

	public function rules() {
		return array(
			array('id, db_date, year, month, day, quarter, week, day_name, month_name', 'required'),
			array('id, year, month, day, quarter, week', 'numerical', 'integerOnly'=>true),
			array('day_name, month_name', 'length', 'max'=>9),
			array('holiday_flag, weekend_flag', 'length', 'max'=>1),
			array('event', 'length', 'max'=>50),
			array('holiday_flag, weekend_flag, event', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, db_date, year, month, day, quarter, week, day_name, month_name, holiday_flag, weekend_flag, event', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'db_date' => Yii::t('app', 'Db Date'),
			'year' => Yii::t('app', 'Year'),
			'month' => Yii::t('app', 'Month'),
			'day' => Yii::t('app', 'Day'),
			'quarter' => Yii::t('app', 'Quarter'),
			'week' => Yii::t('app', 'Week'),
			'day_name' => Yii::t('app', 'Day Name'),
			'month_name' => Yii::t('app', 'Month Name'),
			'holiday_flag' => Yii::t('app', 'Holiday Flag'),
			'weekend_flag' => Yii::t('app', 'Weekend Flag'),
			'event' => Yii::t('app', 'Event'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('db_date', $this->db_date, true);
		$criteria->compare('year', $this->year);
		$criteria->compare('month', $this->month);
		$criteria->compare('day', $this->day);
		$criteria->compare('quarter', $this->quarter);
		$criteria->compare('week', $this->week);
		$criteria->compare('day_name', $this->day_name, true);
		$criteria->compare('month_name', $this->month_name, true);
		$criteria->compare('holiday_flag', $this->holiday_flag, true);
		$criteria->compare('weekend_flag', $this->weekend_flag, true);
		$criteria->compare('event', $this->event, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}