<?php

/**
 * This is the model base class for the table "permission".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Permission".
 *
 * Columns in table "permission" available as properties of the model,
 * followed by relations of table "permission" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $description
 * @property string $group_name
 * @property integer $order_no
 *
 * @property Role[] $roles
 */
abstract class BasePermission extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'permission';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Permission|Permissions', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('id', 'required'),
			array('order_no', 'numerical', 'integerOnly'=>true),
			array('id', 'length', 'max'=>64),
			array('name, group_name', 'length', 'max'=>60),
			array('description', 'safe'),
			array('name, description, group_name, order_no', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description, group_name, order_no', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'roles' => array(self::MANY_MANY, 'Role', 'role_permission(permission_id, role_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'roles' => 'RolePermission',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'group_name' => Yii::t('app', 'Group Name'),
			'order_no' => Yii::t('app', 'Order No'),
			'roles' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('group_name', $this->group_name, true);
		$criteria->compare('order_no', $this->order_no);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}