<?php

/**
 * This is the model base class for the table "exam_prerequisite".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ExamPrerequisite".
 *
 * Columns in table "exam_prerequisite" available as properties of the model,
 * followed by relations of table "exam_prerequisite" available as properties of the model.
 *
 * @property string $exam_subject_id
 * @property string $exam_subject_require_id
 * @property string $minimum_grade
 * @property string $exam_type_id
 * @property string $exam_type_require_id
 *
 * @property ExamSubject $examSubject
 * @property ExamSubject $examSubjectRequire
 * @property ExamType $examType
 * @property ExamType $examTypeRequire
 */
abstract class BaseExamPrerequisite extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'exam_prerequisite';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ExamPrerequisite|ExamPrerequisites', $n);
	}

	public static function representingColumn() {
		return 'minimum_grade';
	}

	public function rules() {
		return array(
			array('exam_subject_id, exam_subject_require_id, exam_type_id, exam_type_require_id', 'required'),
			array('exam_subject_id, exam_subject_require_id, minimum_grade, exam_type_id, exam_type_require_id', 'length', 'max'=>10),
			array('minimum_grade', 'default', 'setOnEmpty' => true, 'value' => null),
			array('exam_subject_id, exam_subject_require_id, minimum_grade, exam_type_id, exam_type_require_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'examSubject' => array(self::BELONGS_TO, 'ExamSubject', 'exam_subject_id'),
			'examSubjectRequire' => array(self::BELONGS_TO, 'ExamSubject', 'exam_subject_require_id'),
			'examType' => array(self::BELONGS_TO, 'ExamType', 'exam_type_id'),
			'examTypeRequire' => array(self::BELONGS_TO, 'ExamType', 'exam_type_require_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'exam_subject_id' => null,
			'exam_subject_require_id' => null,
			'minimum_grade' => Yii::t('app', 'Minimum Grade'),
			'exam_type_id' => null,
			'exam_type_require_id' => null,
			'examSubject' => null,
			'examSubjectRequire' => null,
			'examType' => null,
			'examTypeRequire' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('exam_subject_id', $this->exam_subject_id);
		$criteria->compare('exam_subject_require_id', $this->exam_subject_require_id);
		$criteria->compare('minimum_grade', $this->minimum_grade, true);
		$criteria->compare('exam_type_id', $this->exam_type_id);
		$criteria->compare('exam_type_require_id', $this->exam_type_require_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}