<?php

/**
 * This is the model base class for the table "application_counter".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ApplicationCounter".
 *
 * Columns in table "application_counter" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $app_type
 * @property integer $app_year
 * @property string $current_num
 *
 */
abstract class BaseApplicationCounter extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'application_counter';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ApplicationCounter|ApplicationCounters', $n);
	}

	public static function representingColumn() {
		return array(
			'app_type',
			'app_year',
		);
	}

	public function rules() {
		return array(
			array('app_type, app_year, current_num', 'required'),
			array('app_type, app_year', 'numerical', 'integerOnly'=>true),
			array('current_num', 'length', 'max'=>10),
			array('app_type, app_year, current_num', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'app_type' => Yii::t('app', 'App Type'),
			'app_year' => Yii::t('app', 'App Year'),
			'current_num' => Yii::t('app', 'Current Num'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('app_type', $this->app_type);
		$criteria->compare('app_year', $this->app_year);
		$criteria->compare('current_num', $this->current_num, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}