<?php

/**
 * This is the model base class for the table "exam_default_grade".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ExamDefaultGrade".
 *
 * Columns in table "exam_default_grade" available as properties of the model,
 * followed by relations of table "exam_default_grade" available as properties of the model.
 *
 * @property string $exam_type_id
 * @property string $exam_subject_id
 * @property string $grade
 * @property integer $order_no
 * @property string $description
 *
 * @property ExamSubject $examSubject
 * @property ExamType $examType
 */
abstract class BaseExamDefaultGrade extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'exam_default_grade';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ExamDefaultGrade|ExamDefaultGrades', $n);
	}

	public static function representingColumn() {
		return 'grade';
	}

	public function rules() {
		return array(
			array('exam_type_id, exam_subject_id, grade', 'required'),
			array('order_no', 'numerical', 'integerOnly'=>true),
			array('exam_type_id, exam_subject_id, grade', 'length', 'max'=>10),
			array('description', 'safe'),
			array('order_no, description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('exam_type_id, exam_subject_id, grade, order_no, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'examSubject' => array(self::BELONGS_TO, 'ExamSubject', 'exam_subject_id'),
			'examType' => array(self::BELONGS_TO, 'ExamType', 'exam_type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'exam_type_id' => null,
			'exam_subject_id' => null,
			'grade' => Yii::t('app', 'Grade'),
			'order_no' => Yii::t('app', 'Order No'),
			'description' => Yii::t('app', 'Description'),
			'examSubject' => null,
			'examType' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('exam_type_id', $this->exam_type_id);
		$criteria->compare('exam_subject_id', $this->exam_subject_id);
		$criteria->compare('grade', $this->grade, true);
		$criteria->compare('order_no', $this->order_no);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}