<?php

/**
 * This is the model base class for the table "exam_omr_store".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ExamOmrStore".
 *
 * Columns in table "exam_omr_store" available as properties of the model,
 * followed by relations of table "exam_omr_store" available as properties of the model.
 *
 * @property string $exam_application_id
 * @property string $filename
 *
 * @property ExamApplication $examApplication
 */
abstract class BaseExamOmrStore extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'exam_omr_store';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ExamOmrStore|ExamOmrStores', $n);
	}

	public static function representingColumn() {
		return 'filename';
	}

	public function rules() {
		return array(
			array('exam_application_id', 'required'),
			array('exam_application_id', 'length', 'max'=>10),
			array('filename', 'length', 'max'=>60),
			array('filename', 'default', 'setOnEmpty' => true, 'value' => null),
			array('exam_application_id, filename', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'examApplication' => array(self::BELONGS_TO, 'ExamApplication', 'exam_application_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'exam_application_id' => null,
			'filename' => Yii::t('app', 'Filename'),
			'examApplication' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('exam_application_id', $this->exam_application_id);
		$criteria->compare('filename', $this->filename, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}