<?php

/**
 * This is the model base class for the table "application_omr".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ApplicationOmr".
 *
 * Columns in table "application_omr" available as properties of the model,
 * followed by relations of table "application_omr" available as properties of the model.
 *
 * @property string $exam_set_id
 * @property integer $num
 * @property string $exam_topic_id
 * @property string $user_answer
 * @property string $exam_answer
 * @property integer $is_score
 * @property integer $score
 *
 * @property ExamSet $examSet
 * @property ExamTopic $examTopic
 */
abstract class BaseApplicationOmr extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'application_omr';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ApplicationOmr|ApplicationOmrs', $n);
	}

	public static function representingColumn() {
		return 'exam_set_id';
	}

	public function rules() {
		return array(
			array('exam_set_id, num, exam_topic_id', 'required'),
			array('num, is_score, score', 'numerical', 'integerOnly'=>true),
			array('exam_set_id, exam_topic_id', 'length', 'max'=>10),
			array('user_answer, exam_answer', 'length', 'max'=>64),
			array('user_answer, exam_answer, is_score, score', 'default', 'setOnEmpty' => true, 'value' => null),
			array('exam_set_id, num, exam_topic_id, user_answer, exam_answer, is_score, score', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'examSet' => array(self::BELONGS_TO, 'ExamSet', 'exam_set_id'),
			'examTopic' => array(self::BELONGS_TO, 'ExamTopic', 'exam_topic_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'exam_set_id' => null,
			'num' => Yii::t('app', 'Num'),
			'exam_topic_id' => null,
			'user_answer' => Yii::t('app', 'User Answer'),
			'exam_answer' => Yii::t('app', 'Exam Answer'),
			'is_score' => Yii::t('app', 'Is Score'),
			'score' => Yii::t('app', 'Score'),
			'examSet' => null,
			'examTopic' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('exam_set_id', $this->exam_set_id);
		$criteria->compare('num', $this->num);
		$criteria->compare('exam_topic_id', $this->exam_topic_id);
		$criteria->compare('user_answer', $this->user_answer, true);
		$criteria->compare('exam_answer', $this->exam_answer, true);
		$criteria->compare('is_score', $this->is_score);
		$criteria->compare('score', $this->score);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}