<?php

/**
 * This is the model base class for the table "exam_schedule_department".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ExamScheduleDepartment".
 *
 * Columns in table "exam_schedule_department" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $exam_schedule_id
 * @property integer $code_department_id
 *
 */
abstract class BaseExamScheduleDepartment extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'exam_schedule_department';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ExamScheduleDepartment|ExamScheduleDepartments', $n);
	}

	public static function representingColumn() {
		return array(
			'exam_schedule_id',
			'code_department_id',
		);
	}

	public function rules() {
		return array(
			array('exam_schedule_id, code_department_id', 'required'),
			array('exam_schedule_id, code_department_id', 'numerical', 'integerOnly'=>true),
			array('exam_schedule_id, code_department_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'exam_schedule_id' => Yii::t('app', 'Exam Schedule'),
			'code_department_id' => Yii::t('app', 'Code Department'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('exam_schedule_id', $this->exam_schedule_id);
		$criteria->compare('code_department_id', $this->code_department_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}