<?php

/**
 * This is the model base class for the table "exam_question_method".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ExamQuestionMethod".
 *
 * Columns in table "exam_question_method" available as properties of the model,
 * followed by relations of table "exam_question_method" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property integer $is_auto_check
 * @property integer $is_grade_set
 *
 * @property ExamSetTask[] $examSetTasks
 */
abstract class BaseExamQuestionMethod extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'exam_question_method';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ExamQuestionMethod|ExamQuestionMethods', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('is_auto_check, is_grade_set', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>60),
			array('name, is_auto_check, is_grade_set', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, is_auto_check, is_grade_set', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'examSetTasks' => array(self::HAS_MANY, 'ExamSetTask', 'exam_question_method_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'is_auto_check' => Yii::t('app', 'Is Auto Check'),
			'is_grade_set' => Yii::t('app', 'Is Grade Set'),
			'examSetTasks' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('is_auto_check', $this->is_auto_check);
		$criteria->compare('is_grade_set', $this->is_grade_set);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}