<?php

/**
 * This is the model base class for the table "account_education".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AccountEducation".
 *
 * Columns in table "account_education" available as properties of the model,
 * followed by relations of table "account_education" available as properties of the model.
 *
 * @property string $account_id
 * @property string $item_number
 * @property integer $degree_type
 * @property string $university
 * @property string $country
 * @property integer $year_start
 * @property integer $year_end
 *
 * @property Account $account
 */
abstract class BaseAccountEducation extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'account_education';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AccountEducation|AccountEducations', $n);
	}

	public static function representingColumn() {
		return 'university';
	}

	public function rules() {
		return array(
			array('account_id, item_number', 'required'),
			array('degree_type, year_start, year_end', 'numerical', 'integerOnly'=>true),
			array('account_id, item_number', 'length', 'max'=>10),
			array('university, country', 'length', 'max'=>60),
			array('degree_type, university, country, year_start, year_end', 'default', 'setOnEmpty' => true, 'value' => null),
			array('account_id, item_number, degree_type, university, country, year_start, year_end', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'account' => array(self::BELONGS_TO, 'Account', 'account_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'account_id' => null,
			'item_number' => Yii::t('app', 'Item Number'),
			'degree_type' => Yii::t('app', 'Degree Type'),
			'university' => Yii::t('app', 'University'),
			'country' => Yii::t('app', 'Country'),
			'year_start' => Yii::t('app', 'Year Start'),
			'year_end' => Yii::t('app', 'Year End'),
			'account' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('account_id', $this->account_id);
		$criteria->compare('item_number', $this->item_number, true);
		$criteria->compare('degree_type', $this->degree_type);
		$criteria->compare('university', $this->university, true);
		$criteria->compare('country', $this->country, true);
		$criteria->compare('year_start', $this->year_start);
		$criteria->compare('year_end', $this->year_end);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}