<?php

/**
 * This is the model base class for the table "sms_log".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SmsLog".
 *
 * Columns in table "sms_log" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $message
 * @property string $msisdn
 * @property string $status
 * @property string $detail
 * @property string $transid
 * @property string $groupid
 * @property string $created
 * @property string $modified
 * @property integer $account_id
 *
 */
abstract class BaseSmsLog extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sms_log';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SmsLog|SmsLogs', $n);
	}

	public static function representingColumn() {
		return 'message';
	}

	public function rules() {
		return array(
			array('account_id', 'numerical', 'integerOnly'=>true),
			array('msisdn, status, detail, transid, groupid', 'length', 'max'=>60),
			array('message, created, modified', 'safe'),
			array('message, msisdn, status, detail, transid, groupid, created, modified, account_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, message, msisdn, status, detail, transid, groupid, created, modified, account_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'message' => Yii::t('app', 'Message'),
			'msisdn' => Yii::t('app', 'Msisdn'),
			'status' => Yii::t('app', 'Status'),
			'detail' => Yii::t('app', 'Detail'),
			'transid' => Yii::t('app', 'Transid'),
			'groupid' => Yii::t('app', 'Groupid'),
			'created' => Yii::t('app', 'Created'),
			'modified' => Yii::t('app', 'Modified'),
			'account_id' => Yii::t('app', 'Account'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('message', $this->message, true);
		$criteria->compare('msisdn', $this->msisdn, true);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('detail', $this->detail, true);
		$criteria->compare('transid', $this->transid, true);
		$criteria->compare('groupid', $this->groupid, true);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('modified', $this->modified, true);
		$criteria->compare('account_id', $this->account_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}