<?php

/**
 * This is the model base class for the table "exam_set_item".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ExamSetItem".
 *
 * Columns in table "exam_set_item" available as properties of the model,
 * followed by relations of table "exam_set_item" available as properties of the model.
 *
 * @property string $exam_set_id
 * @property string $num
 * @property string $exam_topic_id
 * @property string $answer
 * @property integer $score
 * @property string $exam_question_type_id
 *
 * @property ExamQuestionMethod $examQuestionType
 * @property ExamSet $examSet
 * @property ExamTopic $examTopic
 */
abstract class BaseExamSetItem extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'exam_set_item';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ExamSetItem|ExamSetItems', $n);
	}

	public static function representingColumn() {
		return 'exam_set_id';
	}

	public function rules() {
		return array(
			array('exam_set_id, num, exam_topic_id', 'required'),
			array('score', 'numerical', 'integerOnly'=>true),
			array('exam_set_id, num, exam_topic_id, exam_question_type_id', 'length', 'max'=>10),
			array('answer', 'length', 'max'=>64),
			array('answer, score, exam_question_type_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('exam_set_id, num, exam_topic_id, answer, score, exam_question_type_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'examQuestionType' => array(self::BELONGS_TO, 'ExamQuestionMethod', 'exam_question_type_id'),
			'examSet' => array(self::BELONGS_TO, 'ExamSet', 'exam_set_id'),
			'examTopic' => array(self::BELONGS_TO, 'ExamTopic', 'exam_topic_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'exam_set_id' => null,
			'num' => Yii::t('app', 'Num'),
			'exam_topic_id' => null,
			'answer' => Yii::t('app', 'Answer'),
			'score' => Yii::t('app', 'Score'),
			'exam_question_type_id' => null,
			'examQuestionType' => null,
			'examSet' => null,
			'examTopic' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('exam_set_id', $this->exam_set_id);
		$criteria->compare('num', $this->num, true);
		$criteria->compare('exam_topic_id', $this->exam_topic_id);
		$criteria->compare('answer', $this->answer, true);
		$criteria->compare('score', $this->score);
		$criteria->compare('exam_question_type_id', $this->exam_question_type_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}