<?php

/**
 * This is the model base class for the table "exam_set_grade".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ExamSetGrade".
 *
 * Columns in table "exam_set_grade" available as properties of the model,
 * followed by relations of table "exam_set_grade" available as properties of the model.
 *
 * @property string $exam_set_id
 * @property string $grade
 * @property integer $min_score
 * @property string $description
 * @property integer $order_no
 *
 * @property ExamSet $examSet
 */
abstract class BaseExamSetGrade extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'exam_set_grade';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ExamSetGrade|ExamSetGrades', $n);
	}

	public static function representingColumn() {
		return 'grade';
	}

	public function rules() {
		return array(
			array('exam_set_id, grade', 'required'),
			array('min_score, order_no', 'numerical', 'integerOnly'=>true),
			array('exam_set_id, grade', 'length', 'max'=>10),
			array('description', 'safe'),
			array('min_score, description, order_no', 'default', 'setOnEmpty' => true, 'value' => null),
			array('exam_set_id, grade, min_score, description, order_no', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'examSet' => array(self::BELONGS_TO, 'ExamSet', 'exam_set_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'exam_set_id' => null,
			'grade' => Yii::t('app', 'Grade'),
			'min_score' => Yii::t('app', 'Min Score'),
			'description' => Yii::t('app', 'Description'),
			'order_no' => Yii::t('app', 'Order No'),
			'examSet' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('exam_set_id', $this->exam_set_id);
		$criteria->compare('grade', $this->grade, true);
		$criteria->compare('min_score', $this->min_score);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('order_no', $this->order_no);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}