<?php

/**
 * This is the model base class for the table "web_menu".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "WebMenu".
 *
 * Columns in table "web_menu" available as properties of the model,
 * followed by relations of table "web_menu" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $name_en
 * @property string $url
 * @property integer $order_no
 * @property integer $is_dropdown
 * @property string $bizrule
 * @property integer $account_class
 * @property integer $account_nation
 *
 * @property WebMenuItem[] $webMenuItems
 */
abstract class BaseWebMenu extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'web_menu';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'WebMenu|WebMenus', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('order_no, is_dropdown, account_class, account_nation', 'numerical', 'integerOnly'=>true),
			array('name, name_en', 'length', 'max'=>150),
			array('url, bizrule', 'safe'),
			array('name, name_en, url, order_no, is_dropdown, bizrule, account_class, account_nation', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, name_en, url, order_no, is_dropdown, bizrule, account_class, account_nation', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'webMenuItems' => array(self::HAS_MANY, 'WebMenuItem', 'web_menu_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'name_en' => Yii::t('app', 'Name En'),
			'url' => Yii::t('app', 'Url'),
			'order_no' => Yii::t('app', 'Order No'),
			'is_dropdown' => Yii::t('app', 'Is Dropdown'),
			'bizrule' => Yii::t('app', 'Bizrule'),
			'account_class' => Yii::t('app', 'Account Class'),
			'account_nation' => Yii::t('app', 'Account Nation'),
			'webMenuItems' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('name_en', $this->name_en, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('order_no', $this->order_no);
		$criteria->compare('is_dropdown', $this->is_dropdown);
		$criteria->compare('bizrule', $this->bizrule, true);
		$criteria->compare('account_class', $this->account_class);
		$criteria->compare('account_nation', $this->account_nation);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}