<?php

/**
 * This is the model base class for the table "code_nationality".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CodeNationality".
 *
 * Columns in table "code_nationality" available as properties of the model,
 * followed by relations of table "code_nationality" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $alpha2
 * @property string $alpha3
 *
 * @property Account[] $accounts
 */
abstract class BaseCodeNationality extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'code_nationality';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CodeNationality|CodeNationalities', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('id', 'required'),
			array('id, alpha3', 'length', 'max'=>3),
			array('name', 'length', 'max'=>60),
			array('alpha2', 'length', 'max'=>2),
			array('name, alpha2, alpha3', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, alpha2, alpha3', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'accounts' => array(self::HAS_MANY, 'Account', 'code_nationality_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'alpha2' => Yii::t('app', 'Alpha2'),
			'alpha3' => Yii::t('app', 'Alpha3'),
			'accounts' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('alpha2', $this->alpha2, true);
		$criteria->compare('alpha3', $this->alpha3, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}