<?php

/**
 * This is the model base class for the table "user_role".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserRole".
 *
 * Columns in table "user_role" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $user_id
 * @property integer $role_id
 *
 */
abstract class BaseUserRole extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_role';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserRole|UserRoles', $n);
	}

	public static function representingColumn() {
		return array(
			'user_id',
			'role_id',
		);
	}

	public function rules() {
		return array(
			array('user_id, role_id', 'required'),
			array('role_id', 'numerical', 'integerOnly'=>true),
			array('user_id', 'length', 'max'=>10),
			array('user_id, role_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'user_id' => null,
			'role_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('role_id', $this->role_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}