<?php

/**
 * This is the model base class for the table "web_mail".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "WebMail".
 *
 * Columns in table "web_mail" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $title
 * @property string $content
 * @property string $date_start
 * @property string $date_end
 * @property string $created
 * @property string $modified
 * @property string $condition
 * @property integer $status
 *
 */
abstract class BaseWebMail extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'web_mail';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'WebMail|WebMails', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('status', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>160),
			array('content, date_start, date_end, created, modified, condition', 'safe'),
			array('title, content, date_start, date_end, created, modified, condition, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, content, date_start, date_end, created, modified, condition, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'content' => Yii::t('app', 'Content'),
			'date_start' => Yii::t('app', 'Date Start'),
			'date_end' => Yii::t('app', 'Date End'),
			'created' => Yii::t('app', 'Created'),
			'modified' => Yii::t('app', 'Modified'),
			'condition' => Yii::t('app', 'Condition'),
			'status' => Yii::t('app', 'Status'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('date_start', $this->date_start, true);
		$criteria->compare('date_end', $this->date_end, true);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('modified', $this->modified, true);
		$criteria->compare('condition', $this->condition, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}