<?php

/**
 * This is the model base class for the table "web_content".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "WebContent".
 *
 * Columns in table "web_content" available as properties of the model,
 * followed by relations of table "web_content" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $date_start
 * @property string $content
 * @property string $created
 * @property string $modified
 * @property string $user_id
 * @property string $date_end
 * @property integer $is_visible
 * @property string $visible_rule
 * @property string $lang
 * @property string $brief
 * @property integer $is_pin
 * @property string $brief_color
 * @property string $vdo
 * @property User $user
 * @property string $custom_link
 */
abstract class BaseWebContent extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'web_content';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'WebContent|WebContents', $n);
	}

	public static function representingColumn() {
		return 'lang';
	}

	public function rules() {
		return array(
			array('is_visible, is_pin', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>150),
			array('custom_link', 'length', 'max'=>500),
			array('user_id, brief_color', 'length', 'max'=>10),
			array('lang', 'length', 'max'=>2),
			array('date_start, content, created, modified, date_end, visible_rule, brief, vdo', 'safe'),
			array('name, date_start, content, created, modified, user_id, date_end, is_visible, visible_rule, lang, brief, is_pin, brief_color, vdo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, date_start, content, created, modified, user_id, date_end, is_visible, visible_rule, lang, brief, is_pin, brief_color, vdo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'date_start' => Yii::t('app', 'Date Start'),
			'content' => Yii::t('app', 'Content'),
			'created' => Yii::t('app', 'Created'),
			'modified' => Yii::t('app', 'Modified'),
			'user_id' => null,
			'date_end' => Yii::t('app', 'Date End'),
			'is_visible' => Yii::t('app', 'Is Visible'),
			'visible_rule' => Yii::t('app', 'Visible Rule'),
			'lang' => Yii::t('app', 'Lang'),
			'brief' => Yii::t('app', 'Brief'),
			'is_pin' => Yii::t('app', 'Is Pin'),
			'brief_color' => Yii::t('app', 'Brief Color'),
			'vdo' => Yii::t('app', 'Vdo'),
			'user' => null,
	      'custom_link' => Yii::t('app', 'Custom Link'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('date_start', $this->date_start, true);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('modified', $this->modified, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('date_end', $this->date_end, true);
		$criteria->compare('is_visible', $this->is_visible);
		$criteria->compare('visible_rule', $this->visible_rule, true);
		$criteria->compare('lang', $this->lang, true);
		$criteria->compare('brief', $this->brief, true);
		$criteria->compare('is_pin', $this->is_pin);
		$criteria->compare('brief_color', $this->brief_color, true);
		$criteria->compare('vdo', $this->vdo, true);
		$criteria->compare('custom_link', $this->custom_link, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}