<?php

/**
 * This is the model base class for the table "code_amphur".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CodeAmphur".
 *
 * Columns in table "code_amphur" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string grade1
 * @property string grade2
 * @property string grade3
 * @property string grade4
 * @property integer subject_count
 * @property integer order_index
 *
 */
abstract class BaseExamResultLevelOrder extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'exam_result_level_order';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CodeAmphur|CodeAmphurs', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('id, subject_count, order_index', 'numerical', 'integerOnly'=>true),
			array('grade1, grade2, grade3, grade4', 'length', 'max'=>100),
			//array('id, order_index', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, subject_count', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('grade1', $this->grade1);
		$criteria->compare('grade2', $this->grade2);
		$criteria->compare('grade3', $this->grade3);
		$criteria->compare('grade4', $this->grade4);
		$criteria->compare('order_index', $this->order_index);
		$criteria->compare('subject_count', $this->subject_count);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}