<?php

/**
 * This is the model base class for the table "exam_application_exam_set".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ExamApplicationExamSet".
 *
 * Columns in table "exam_application_exam_set" available as properties of the model,
 * followed by relations of table "exam_application_exam_set" available as properties of the model.
 *
 * @property string $exam_application_id
 * @property string $exam_schedule_id
 * @property string $exam_set_id
 * @property string $exam_subject_id
 * @property string $grade
 * @property integer $score
 * @property string $raw_data
 * @property string $created
 * @property string $modified
 * @property integer $is_border_line
 * @property integer $score_update
 * @property string $grade_update
 * @property string $update_date
 * @property string $update_user_id
 * @property string $approve_id
 * @property integer $is_approved
 * @property integer $is_update
 * @property string $grade_expire
 * @property integer $is_grade_confirm
 * @property string $grade_confirm_date
 * @property integer $grade_confirm_user_id
 * @property string $all_data
 * @property string $teacher_1
 * @property string $teacher_2
 * @property string $teacher_1_name
 * @property string $teacher_2_name
 * @property string $exam_subject_extra
 *
 * @property ExamApplication $examApplication
 * @property ExamSchedule $examSchedule
 */
abstract class BaseExamApplicationExamSet extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'exam_application_exam_set';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ExamApplicationExamSet|ExamApplicationExamSets', $n);
	}

	public static function representingColumn() {
		return 'exam_set_id';
	}

	public function rules() {
		return array(
			array('exam_application_id, exam_schedule_id, exam_set_id', 'required'),
			array('score, is_border_line, score_update, is_approved, is_update, is_grade_confirm, grade_confirm_user_id', 'numerical', 'integerOnly'=>true),
			array('exam_application_id, exam_schedule_id, exam_set_id, exam_subject_id, update_user_id, approve_id', 'length', 'max'=>10),
			array('grade, grade_update, exam_subject_extra', 'length', 'max'=>60),
			array('teacher_1, teacher_2', 'length', 'max'=>2),
			array('teacher_1_name, teacher_2_name', 'length', 'max'=>160),
			array('raw_data, created, modified, update_date, grade_expire, grade_confirm_date, all_data', 'safe'),
			array('exam_subject_id, grade, score, raw_data, created, modified, is_border_line, score_update, grade_update, update_date, update_user_id, approve_id, is_approved, is_update, grade_expire, is_grade_confirm, grade_confirm_date, grade_confirm_user_id, all_data, teacher_1, teacher_2, teacher_1_name, teacher_2_name, exam_subject_extra', 'default', 'setOnEmpty' => true, 'value' => null),
			array('exam_application_id, exam_schedule_id, exam_set_id, exam_subject_id, grade, score, raw_data, created, modified, is_border_line, score_update, grade_update, update_date, update_user_id, approve_id, is_approved, is_update, grade_expire, is_grade_confirm, grade_confirm_date, grade_confirm_user_id, all_data, teacher_1, teacher_2, teacher_1_name, teacher_2_name, exam_subject_extra', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'examApplication' => array(self::BELONGS_TO, 'ExamApplication', 'exam_application_id'),
			'examSchedule' => array(self::BELONGS_TO, 'ExamSchedule', 'exam_schedule_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'exam_application_id' => null,
			'exam_schedule_id' => null,
			'exam_set_id' => Yii::t('app', 'Exam Set'),
			'exam_subject_id' => Yii::t('app', 'Exam Subject'),
			'grade' => Yii::t('app', 'Grade'),
			'score' => Yii::t('app', 'Score'),
			'raw_data' => Yii::t('app', 'Raw Data'),
			'created' => Yii::t('app', 'Created'),
			'modified' => Yii::t('app', 'Modified'),
			'is_border_line' => Yii::t('app', 'Is Border Line'),
			'score_update' => Yii::t('app', 'Score Update'),
			'grade_update' => Yii::t('app', 'Grade Update'),
			'update_date' => Yii::t('app', 'Update Date'),
			'update_user_id' => Yii::t('app', 'Update User'),
			'approve_id' => Yii::t('app', 'Approve'),
			'is_approved' => Yii::t('app', 'Is Approved'),
			'is_update' => Yii::t('app', 'Is Update'),
			'grade_expire' => Yii::t('app', 'Grade Expire'),
			'is_grade_confirm' => Yii::t('app', 'Is Grade Confirm'),
			'grade_confirm_date' => Yii::t('app', 'Grade Confirm Date'),
			'grade_confirm_user_id' => Yii::t('app', 'Grade Confirm User'),
			'all_data' => Yii::t('app', 'All Data'),
			'teacher_1' => Yii::t('app', 'Teacher 1'),
			'teacher_2' => Yii::t('app', 'Teacher 2'),
			'teacher_1_name' => Yii::t('app', 'Teacher 1 Name'),
			'teacher_2_name' => Yii::t('app', 'Teacher 2 Name'),
			'exam_subject_extra' => Yii::t('app', 'Exam Subject Extra'),
			'examApplication' => null,
			'examSchedule' => null,
		);
	}

 

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('exam_application_id', $this->exam_application_id);
		$criteria->compare('exam_schedule_id', $this->exam_schedule_id);
		$criteria->compare('exam_set_id', $this->exam_set_id, true);
		$criteria->compare('exam_subject_id', $this->exam_subject_id, true);
		$criteria->compare('grade', $this->grade, true);
		$criteria->compare('score', $this->score);
		$criteria->compare('raw_data', $this->raw_data, true);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('modified', $this->modified, true);
		$criteria->compare('is_border_line', $this->is_border_line);
		$criteria->compare('score_update', $this->score_update);
		$criteria->compare('grade_update', $this->grade_update, true);
		$criteria->compare('update_date', $this->update_date, true);
		$criteria->compare('update_user_id', $this->update_user_id, true);
		$criteria->compare('approve_id', $this->approve_id, true);
		$criteria->compare('is_approved', $this->is_approved);
		$criteria->compare('is_update', $this->is_update);
		$criteria->compare('grade_expire', $this->grade_expire, true);
		$criteria->compare('is_grade_confirm', $this->is_grade_confirm);
		$criteria->compare('grade_confirm_date', $this->grade_confirm_date, true);
		$criteria->compare('grade_confirm_user_id', $this->grade_confirm_user_id);
		$criteria->compare('all_data', $this->all_data, true);
		$criteria->compare('teacher_1', $this->teacher_1, true);
		$criteria->compare('teacher_2', $this->teacher_2, true);
		$criteria->compare('teacher_1_name', $this->teacher_1_name, true);
		$criteria->compare('teacher_2_name', $this->teacher_2_name, true);
		$criteria->compare('exam_subject_extra', $this->exam_subject_extra, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}