<?php

/**
 * This is the model base class for the table "exam_schedule_objective".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ExamScheduleObjective".
 *
 * Columns in table "exam_schedule_objective" available as properties of the model,
 * followed by relations of table "exam_schedule_objective" available as properties of the model.
 *
 * @property integer $id
 * @property string $exam_schedule_id
 * @property string $name_th
 * @property string $description
 * @property integer $is_private
 * @property string $period_start
 * @property string $period_end
 * @property string $name_en

 *
 * @property ExamSchedule $examSchedule
 */
abstract class BaseExamScheduleObjective extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'exam_schedule_objective';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ExamScheduleObjective|ExamScheduleObjectives', $n);
	}

	public static function representingColumn() {
		return 'name_th';
	}

	public function rules() {
		return array(
			array('id, exam_schedule_id', 'required'),
			array('id, is_private', 'numerical', 'integerOnly'=>true),
			array('exam_schedule_id', 'length', 'max'=>10),
			array('name_th, name_en', 'length', 'max'=>160),
			array('description, period_start, period_end', 'safe'),
			array('name_th, description, is_private, period_start, period_end, name_en', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, exam_schedule_id, name_th, description, is_private, period_start, period_end, name_en', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'examSchedule' => array(self::BELONGS_TO, 'ExamSchedule', 'exam_schedule_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'exam_schedule_id' => null,
			'name_th' => Yii::t('app', 'Name Th'),
			'description' => Yii::t('app', 'Description'),
			'is_private' => Yii::t('app', 'Is Private'),
			'period_start' => Yii::t('app', 'Period Start'),
			'period_end' => Yii::t('app', 'Period End'),
			'name_en' => Yii::t('app', 'Name En'),
			'examSchedule' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('exam_schedule_id', $this->exam_schedule_id);
		$criteria->compare('name_th', $this->name_th, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('is_private', $this->is_private);
		$criteria->compare('period_start', $this->period_start, true);
		$criteria->compare('period_end', $this->period_end, true);
		$criteria->compare('name_en', $this->name_en, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}