<?php

/**
 * This is the model base class for the table "income_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "IncomeType".
 *
 * Columns in table "income_type" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $name
 * @property string $comp_code
 *
 */
abstract class BaseIncomeType extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'income_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'IncomeType|IncomeTypes', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('id, name', 'required'),
			array('id', 'length', 'max'=>10),
			array('name, comp_code', 'length', 'max'=>60),
			array('comp_code', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, comp_code', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'comp_code' => Yii::t('app', 'Comp Code'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('comp_code', $this->comp_code, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}