<?php

/**
 * This is the model base class for the table "code_place".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CodePlace".
 *
 * Columns in table "code_place" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $name
 * @property string $name_en
 *
 */
abstract class BaseCodePlace extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'code_place';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CodePlace|CodePlaces', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, name_en', 'length', 'max'=>150),
			array('name, name_en', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, name_en', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'name_en' => Yii::t('app', 'Name En'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('name_en', $this->name_en, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}