<?php

/**
 * This is the model base class for the table "web_faq".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "WebFAQ".
 *
 * Columns in table "web_faq" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $question
 * @property string $content
 * @property integer $order_no
 *
 */
abstract class BaseWebFAQ extends ActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'web_faq';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'WebFAQ|WebFAQ', $n);
	}

	public static function representingColumn() {
		return 'question';
	}

	public function rules() {
		return array(
			array('order_no', 'numerical', 'integerOnly'=>true),
			array('question', 'length', 'max'=>250),
			array('question, content, order_no', 'default', 'setOnEmpty' => true, 'value' => null),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'question' => Yii::t('app', 'Question'),
			'content' => Yii::t('app', 'Content'),
			'order_no' => Yii::t('app', 'Order No'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('question', $this->question, true);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('order_no', $this->order_no);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}